const firebaseConfig={apiKey:"AIzaSyBu2RrQn8cAwwWaLtw5O8Omwn4-NzHWuc0",authDomain:"kor-app-fa47e.firebaseapp.com",projectId:"kor-app-fa47e",storageBucket:"kor-app-fa47e.firebasestorage.app",messagingSenderId:"397749083935",appId:"1:397749083935:web:51c7c"};
if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);
const db=firebase.firestore();

const state={currentUser:"",currentEventId:"",isAdmin:false,unsubscribeParties:null,parties:[],events:[{id:"viking",name:"바이킹의 역습",desc:"기존 파티 시스템 유지"},{id:"ruins",name:"유적 쟁탈",desc:"운영진 전용 파티 생성 / 15인 고정"}],editingRuinsPartyId:""};
const TEST_HIDDEN_PREFIXES=["test","tester","테스트","운영테스트"];
const el={loginScreen:document.getElementById("loginScreen"),homeScreen:document.getElementById("homeScreen"),eventScreen:document.getElementById("eventScreen"),nicknameInput:document.getElementById("nicknameInput"),myNameBtn:document.getElementById("myNameBtn"),adminMenuBtn:document.getElementById("adminMenuBtn"),adminMenu:document.getElementById("adminMenu"),homeSummary:document.getElementById("homeSummary"),homeEventCards:document.getElementById("homeEventCards"),partyList:document.getElementById("partyList"),eventTitle:document.getElementById("eventTitle"),eventDesc:document.getElementById("eventDesc"),createPartyBtn:document.getElementById("createPartyBtn"),modalOverlay:document.getElementById("modalOverlay"),userModal:document.getElementById("userModal"),joinedUsers:document.getElementById("joinedUsers"),notJoinedUsers:document.getElementById("notJoinedUsers"),logModal:document.getElementById("logModal"),logList:document.getElementById("logList"),ruinsCreateModal:document.getElementById("ruinsCreateModal"),ruinsModalTitle:document.getElementById("ruinsModalTitle"),ruinsSubmitBtn:document.getElementById("ruinsSubmitBtn"),ruinNameInput:document.getElementById("ruinNameInput"),utcMonth:document.getElementById("utcMonth"),utcDay:document.getElementById("utcDay"),utcHour:document.getElementById("utcHour")};

function escapeHtml(s){return String(s??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;");}
function escapeJs(s){return String(s??"").replace(/\\/g,"\\\\").replace(/'/g,"\\'");}
function normalizeMembers(m){return Array.isArray(m)?m.filter(v=>typeof v==="string"&&v.trim()!==""):[];}
function isHiddenTestNickname(name){const lowered=String(name||"").trim().toLowerCase();return TEST_HIDDEN_PREFIXES.some(prefix=>lowered.startsWith(String(prefix).toLowerCase()));}
function showOnly(name){el.loginScreen.classList.add("hidden");el.homeScreen.classList.add("hidden");el.eventScreen.classList.add("hidden");if(name==="login")el.loginScreen.classList.remove("hidden");if(name==="home")el.homeScreen.classList.remove("hidden");if(name==="event")el.eventScreen.classList.remove("hidden");}
function eventRef(id){return db.collection("events").doc(id);}
function partiesRef(id){return eventRef(id).collection("parties");}
function setTopTabs(active){document.querySelectorAll(".tab-btn").forEach(btn=>btn.classList.remove("active"));if(active==="home")document.querySelectorAll(".tab-btn")[0].classList.add("active");if(active==="viking")document.querySelectorAll(".tab-btn")[1].classList.add("active");if(active==="ruins")document.querySelectorAll(".tab-btn")[2].classList.add("active");}
function updateUserBadge(){el.myNameBtn.textContent=state.currentUser?`${state.currentUser}${state.isAdmin?" (운영진)":""}`:"로그인 안 됨";if(state.isAdmin)el.adminMenuBtn.classList.remove("hidden");else{el.adminMenuBtn.classList.add("hidden");closeAdminMenu();}}
function toggleAdminMenu(){el.adminMenu.classList.toggle("hidden");}
function closeAdminMenu(){el.adminMenu.classList.add("hidden");}
window.toggleAdminMenu=toggleAdminMenu;window.closeAdminMenu=closeAdminMenu;
function openOverlay(){el.modalOverlay.classList.remove("hidden");}
function closeOverlay(){if(!el.userModal.classList.contains("hidden"))return;if(!el.logModal.classList.contains("hidden"))return;if(!el.ruinsCreateModal.classList.contains("hidden"))return;el.modalOverlay.classList.add("hidden");}
el.modalOverlay.addEventListener("click",()=>{closeUserModal();closeLogModal();closeRuinsCreateModal();});

async function ensureEventDocs(){for(const e of state.events){await eventRef(e.id).set({name:e.name,desc:e.desc},{merge:true});}}
async function ensureUserDoc(name){await db.collection("users").doc(name).set({nickname:name,lastLoginAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});}
async function refreshAdmin(){state.isAdmin=(await db.collection("admins").doc(state.currentUser).get()).exists;updateUserBadge();}
async function writeAdminLog(action,payload){if(!state.isAdmin)return;await db.collection("adminLogs").add({action,payload:payload||{},event:state.currentEventId||"",admin:state.currentUser,createdAt:firebase.firestore.FieldValue.serverTimestamp(),undone:false});}

function initRuinsSelects(){for(let i=1;i<=12;i++)el.utcMonth.insertAdjacentHTML("beforeend",`<option value="${i}">${i}월</option>`);for(let i=1;i<=31;i++)el.utcDay.insertAdjacentHTML("beforeend",`<option value="${i}">${i}일</option>`);for(let i=0;i<=23;i++)el.utcHour.insertAdjacentHTML("beforeend",`<option value="${i}">${String(i).padStart(2,"0")}:00</option>`);}

function getNicknameValue(){const direct=el.nicknameInput&&typeof el.nicknameInput.value==="string"?el.nicknameInput.value:"";const byId1=document.getElementById("nicknameInput")?.value||"";const byId2=document.getElementById("nickname")?.value||"";const active=document.activeElement&&typeof document.activeElement.value==="string"?document.activeElement.value:"";return String(direct||byId1||byId2||active||"").trim();}
async function login(){const name=getNicknameValue();if(!name){alert("닉네임을 입력하세요.");if(el.nicknameInput)el.nicknameInput.focus();return;}state.currentUser=name;if(el.nicknameInput)el.nicknameInput.value=name;localStorage.setItem("partyAppUser",name);await ensureUserDoc(name);await refreshAdmin();await ensureEventDocs();goHome();}
if(el.nicknameInput){el.nicknameInput.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();login();}});}
window.login=login;
async function logout(){if(state.unsubscribeParties){state.unsubscribeParties();state.unsubscribeParties=null;}state.currentUser="";state.currentEventId="";state.isAdmin=false;state.parties=[];localStorage.removeItem("partyAppUser");localStorage.removeItem("partyAppEvent");updateUserBadge();showOnly("login");setTopTabs("");}
window.logout=logout;

async function tryAutoLogin(){try{initRuinsSelects();const savedUser=localStorage.getItem("partyAppUser");await ensureEventDocs();if(!savedUser){updateUserBadge();showOnly("login");return;}state.currentUser=savedUser;await ensureUserDoc(savedUser);await refreshAdmin();const savedEvent=localStorage.getItem("partyAppEvent");if(savedEvent){openEvent(savedEvent);}else{goHome();}}catch(e){console.error(e);alert("기본 데이터를 불러오는 중 오류가 발생했습니다.");showOnly("login");}}

async function renderHomeSummary(){const usersSnap=await db.collection("users").get();const adminsSnap=await db.collection("admins").get();el.homeSummary.innerHTML=`<div class="summary-card"><div class="muted">전체 유저</div><div class="big-number">${usersSnap.size}</div></div><div class="summary-card"><div class="muted">이벤트 수</div><div class="big-number">${state.events.length}</div></div><div class="summary-card"><div class="muted">운영진 수</div><div class="big-number">${adminsSnap.size}</div></div>`;}
function renderHomeEventCards(){el.homeEventCards.innerHTML=state.events.map(e=>`<div class="event-card"><h3>${escapeHtml(e.name)}</h3><p>${escapeHtml(e.desc)}</p><div class="actions"><button onclick="openEvent('${escapeJs(e.id)}')">들어가기</button></div></div>`).join("");}
async function goHome(){if(state.unsubscribeParties){state.unsubscribeParties();state.unsubscribeParties=null;}state.currentEventId="";localStorage.removeItem("partyAppEvent");setTopTabs("home");renderHomeEventCards();await renderHomeSummary();showOnly("home");}
window.goHome=goHome;

async function openEvent(id){state.currentEventId=id;localStorage.setItem("partyAppEvent",id);setTopTabs(id);const meta=state.events.find(v=>v.id===id);el.eventTitle.textContent=meta?meta.name:id;el.eventDesc.textContent=meta?meta.desc:"";el.createPartyBtn.textContent=id==="ruins"?"유적 파티 생성":"파티 생성";showOnly("event");subscribeParties();}
window.openEvent=openEvent;

function subscribeParties(){if(state.unsubscribeParties){state.unsubscribeParties();state.unsubscribeParties=null;}state.unsubscribeParties=partiesRef(state.currentEventId).onSnapshot(snap=>{state.parties=snap.docs.map(doc=>{const d=doc.data()||{};return{id:doc.id,name:d.name||"",ruinName:d.ruinName||"",event:d.event||state.currentEventId,createdBy:d.createdBy||"",members:normalizeMembers(d.members),rallyLeader:d.rallyLeader||"",timeUTC:d.timeUTC||null,maxMembers:Number(d.maxMembers||0),type:d.type||""};});state.parties.sort(sortParties);renderPartyList();},err=>{console.error(err);alert("기본 데이터를 불러오는 중 오류가 발생했습니다.");});}
function sortParties(a,b){if(state.currentEventId==="ruins"){return getTimeValue(a.timeUTC)-getTimeValue(b.timeUTC);}return String(a.name).localeCompare(String(b.name),"ko");}
function getTimeValue(t){if(!t)return Number.MAX_SAFE_INTEGER;if(typeof t.toDate==="function")return t.toDate().getTime();if(t.seconds)return t.seconds*1000;const n=new Date(t).getTime();return Number.isFinite(n)?n:Number.MAX_SAFE_INTEGER;}
function toDate(t){if(!t)return null;if(typeof t.toDate==="function")return t.toDate();if(t.seconds)return new Date(t.seconds*1000);const d=new Date(t);return Number.isNaN(d.getTime())?null:d;}
function formatKST(t){const d=toDate(t);if(!d)return"-";return`${d.getMonth()+1}/${d.getDate()} ${String(d.getHours()).padStart(2,"0")}:00`;}
function formatUTC(t){const d=toDate(t);if(!d)return"-";return`${d.getUTCMonth()+1}/${d.getUTCDate()} ${String(d.getUTCHours()).padStart(2,"0")}:00`;}
function calcPower(memberCount){const base=Math.max(memberCount-1,1);return Math.floor((920000/base)/1000)*1000;}
function myParty(){if(state.currentEventId!=="viking")return null;return state.parties.find(p=>p.members.includes(state.currentUser))||null;}

function renderPartyList(){if(!state.parties.length){el.partyList.innerHTML=`<div class="empty-card">아직 생성된 파티가 없습니다.</div>`;return;}el.partyList.innerHTML=state.parties.map(p=>state.currentEventId==="ruins"?renderRuinsCard(p):renderVikingCard(p)).join("");}
function renderVikingCard(p){const meJoined=p.members.includes(state.currentUser);const canDelete=state.isAdmin||p.createdBy===state.currentUser;const canKick=state.isAdmin||p.createdBy===state.currentUser;const maxMembers=Number(p.maxMembers||0);const isFull=maxMembers>0&&p.members.length>=maxMembers;const membersHtml=p.members.map(name=>`<div class="member-line"><span class="${name===state.currentUser?"my-name":""}">${name===p.createdBy?"👑 ":""}${escapeHtml(name)}</span>${canKick&&name!==p.createdBy?`<button class="inline-btn" onclick="kickMember('${escapeJs(p.id)}','${escapeJs(name)}')">✖</button>`:""}</div>`).join("");return`<div class="party-card"><div class="party-title">${escapeHtml(p.name)}</div><div class="party-sub">파티장: ${escapeHtml(p.createdBy||"-")}</div><div class="party-sub">인원: ${p.members.length}${maxMembers>0?`/${maxMembers}`:""}명</div><div class="member-list">${membersHtml||'<div class="member-line"><span>참가자가 없습니다.</span></div>'}</div><div class="card-actions">${!meJoined&&!isFull?`<button onclick="joinParty('${escapeJs(p.id)}')">참가</button>`:""}${meJoined?`<button onclick="leaveParty('${escapeJs(p.id)}')">취소</button>`:""}${canDelete?`<button onclick="deleteParty('${escapeJs(p.id)}')">삭제</button>`:""}</div></div>`;}
function renderRuinsCard(p){const members=[...p.members].sort((a,b)=>a===p.rallyLeader?-1:b===p.rallyLeader?1:a.localeCompare(b,"ko"));const meJoined=members.includes(state.currentUser);const power=calcPower(members.length).toLocaleString("ko-KR");const membersHtml=members.map(name=>`<div class="member-line"><span class="${name===state.currentUser?"my-name":""}">${name===p.rallyLeader?"👑 ":""}${escapeHtml(name)}</span>${state.isAdmin&&name!==p.rallyLeader?`<button class="inline-btn" onclick="setRallyLeader('${escapeJs(p.id)}','${escapeJs(name)}')">👍</button>`:""}${state.isAdmin?`<button class="inline-btn" onclick="kickMember('${escapeJs(p.id)}','${escapeJs(name)}')">✖</button>`:""}</div>`).join("");return`<div class="party-card"><div class="party-title">유적명: ${escapeHtml(p.ruinName||p.name)}</div><div class="party-sub">시간: ${formatKST(p.timeUTC)}</div><div class="party-sub">UTC ${formatUTC(p.timeUTC)}</div><div class="party-sub">병력수: ${power}명</div><div class="party-sub">인원: ${members.length}/15</div><div class="member-list compact">${membersHtml||'<div class="member-line"><span>참가자가 없습니다.</span></div>'}</div><div class="card-actions">${!meJoined&&members.length<15?`<button onclick="joinParty('${escapeJs(p.id)}')">참가</button>`:""}${meJoined?`<button onclick="leaveParty('${escapeJs(p.id)}')">취소</button>`:""}${state.isAdmin?`<button onclick="openRuinsEditModal('${escapeJs(p.id)}')">수정</button><button onclick="deleteParty('${escapeJs(p.id)}')">삭제</button>`:""}<button onclick="copyRuinsNotice('${escapeJs(p.id)}')">복사</button></div></div>`;}

async function createParty(){if(state.currentEventId==="viking")return createVikingParty();if(state.currentEventId==="ruins")return openRuinsCreateModal();}
window.createParty=createParty;
async function createVikingParty(){const name=(prompt("파티 이름을 입력하세요.")||"").trim();if(!name)return;if(myParty()){alert("이미 다른 파티에 참여 중입니다.");return;}const maxPrompt=`최대 인원을 입력하세요.
예: 6`;const maxInput=(prompt(maxPrompt)||"").trim();const maxMembers=Number(maxInput);if(!Number.isInteger(maxMembers)||maxMembers<1){alert("최대 인원은 1 이상의 숫자로 입력하세요.");return;}const dup=await partiesRef("viking").where("name","==",name).get();if(!dup.empty){alert("같은 이름의 파티가 이미 있습니다.");return;}await partiesRef("viking").add({type:"viking",event:"viking",name,createdBy:state.currentUser,members:[state.currentUser],maxMembers,createdAt:firebase.firestore.FieldValue.serverTimestamp()});}
function openRuinsCreateModal(){if(!state.isAdmin){alert("유적 파티는 운영진만 생성할 수 있습니다.");return;}state.editingRuinsPartyId="";if(el.ruinsModalTitle)el.ruinsModalTitle.textContent="유적 파티 생성";if(el.ruinsSubmitBtn)el.ruinsSubmitBtn.textContent="생성";el.ruinNameInput.value="";el.utcMonth.value="1";el.utcDay.value="1";el.utcHour.value="0";openOverlay();el.ruinsCreateModal.classList.remove("hidden");}
async function openRuinsEditModal(partyId){if(!state.isAdmin){alert("권한이 없습니다.");return;}const p=state.parties.find(v=>v.id===partyId);if(!p){alert("파티를 찾을 수 없습니다.");return;}state.editingRuinsPartyId=partyId;if(el.ruinsModalTitle)el.ruinsModalTitle.textContent="유적 파티 수정";if(el.ruinsSubmitBtn)el.ruinsSubmitBtn.textContent="수정";el.ruinNameInput.value=p.ruinName||p.name||"";const d=toDate(p.timeUTC);if(d){el.utcMonth.value=String(d.getUTCMonth()+1);el.utcDay.value=String(d.getUTCDate());el.utcHour.value=String(d.getUTCHours());}openOverlay();el.ruinsCreateModal.classList.remove("hidden");}
window.openRuinsEditModal=openRuinsEditModal;
function closeRuinsCreateModal(){state.editingRuinsPartyId="";if(el.ruinsModalTitle)el.ruinsModalTitle.textContent="유적 파티 생성";if(el.ruinsSubmitBtn)el.ruinsSubmitBtn.textContent="생성";el.ruinsCreateModal.classList.add("hidden");closeOverlay();}
window.openRuinsCreateModal=openRuinsCreateModal;window.closeRuinsCreateModal=closeRuinsCreateModal;
async function submitRuinsParty(){if(!state.isAdmin){alert("권한이 없습니다.");return;}const ruinName=(el.ruinNameInput.value||"").trim();const m=Number(el.utcMonth.value),d=Number(el.utcDay.value),h=Number(el.utcHour.value);if(!ruinName){alert("유적명을 입력하세요.");return;}if(!m||!d||h<0||h>23){alert("UTC 날짜/시간을 선택하세요.");return;}const year=new Date().getUTCFullYear();const utcDate=new Date(Date.UTC(year,m-1,d,h,0,0,0));if(state.editingRuinsPartyId){const ref=partiesRef("ruins").doc(state.editingRuinsPartyId);await ref.update({name:ruinName,ruinName,timeUTC:utcDate});await writeAdminLog("update_ruins_party",{partyId:state.editingRuinsPartyId,ruinName,month:m,day:d,hour:h});}else{await partiesRef("ruins").add({type:"ruins",event:"ruins",name:ruinName,ruinName,createdBy:state.currentUser,members:[],rallyLeader:"",maxMembers:15,timeUTC:utcDate,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await writeAdminLog("create_ruins_party",{ruinName,month:m,day:d,hour:h});}closeRuinsCreateModal();}
window.submitRuinsParty=submitRuinsParty;

async function joinParty(id){if(state.currentEventId==="viking"&&myParty()){alert("이미 다른 파티에 참여 중입니다.");return;}const ref=partiesRef(state.currentEventId).doc(id);const snap=await ref.get();if(!snap.exists){alert("파티를 찾을 수 없습니다.");return;}const d=snap.data()||{};const members=normalizeMembers(d.members);if(state.currentEventId==="ruins"&&members.length>=15){alert("유적 파티는 최대 15명입니다.");return;}if(state.currentEventId==="viking"&&Number(d.maxMembers||0)>0&&members.length>=Number(d.maxMembers)){alert("이 파티는 정원이 가득 찼습니다.");return;}if(members.includes(state.currentUser)){if(state.currentEventId==="ruins"){alert("이미 이 유적 파티에 신청되어 있습니다.");}return;}members.push(state.currentUser);await ref.update({members});}
window.joinParty=joinParty;
async function leaveParty(id){const ref=partiesRef(state.currentEventId).doc(id);const snap=await ref.get();if(!snap.exists)return;const d=snap.data()||{};let members=normalizeMembers(d.members).filter(v=>v!==state.currentUser);const updates={members};if(state.currentEventId==="ruins"&&d.rallyLeader===state.currentUser)updates.rallyLeader=members[0]||"";await ref.update(updates);}
window.leaveParty=leaveParty;
async function deleteParty(id){const ref=partiesRef(state.currentEventId).doc(id);const snap=await ref.get();if(!snap.exists)return;const d=snap.data()||{};const ok=state.isAdmin||d.createdBy===state.currentUser;if(!ok){alert("삭제 권한이 없습니다.");return;}if(!confirm(state.currentEventId==="ruins"?"정말 이 유적 파티를 삭제하시겠습니까?":"정말 이 파티를 삭제하시겠습니까?"))return;await ref.delete();if(state.isAdmin)await writeAdminLog("delete_party",{partyId:id,name:d.name||"",ruinName:d.ruinName||""});}
window.deleteParty=deleteParty;
async function kickMember(id,name){const p=state.parties.find(v=>v.id===id);if(!p)return;const ok=state.isAdmin||p.createdBy===state.currentUser;if(!ok){alert("추방 권한이 없습니다.");return;}if(!confirm(`${name} 님을 추방하시겠습니까?`))return;const ref=partiesRef(state.currentEventId).doc(id);const members=normalizeMembers(p.members).filter(v=>v!==name);const updates={members};if(state.currentEventId==="ruins"&&p.rallyLeader===name)updates.rallyLeader=members[0]||"";await ref.update(updates);if(state.isAdmin)await writeAdminLog("kick_member",{partyId:id,memberName:name});}
window.kickMember=kickMember;
async function setRallyLeader(id,name){if(!state.isAdmin){alert("권한이 없습니다.");return;}if(!confirm(`${name} 님을 집결장으로 지정하시겠습니까?`))return;const p=state.parties.find(v=>v.id===id);if(!p||!p.members.includes(name)){alert("해당 사용자는 현재 파티원이 아닙니다.");return;}await partiesRef("ruins").doc(id).update({rallyLeader:name});await writeAdminLog("set_rally_leader",{partyId:id,memberName:name});}
window.setRallyLeader=setRallyLeader;

// ===== 유적 공지 복사 =====
function copyRuinsNotice(partyId){const p=state.parties.find(v=>v.id===partyId);if(!p)return;const members=[...p.members];const leader=p.rallyLeader||"";const others=members.filter(n=>n!==leader);const power=calcPower(members.length).toLocaleString("ko-KR");const kstTime=toDate(p.timeUTC)?`${String(toDate(p.timeUTC).getHours()).padStart(2,"0")}:00`:"-";const utcTime=toDate(p.timeUTC)?`${String(toDate(p.timeUTC).getUTCHours()).padStart(2,"0")}:00`:"-";const title=(p.ruinName||p.name||"")+" 명단";const text=`${title}
시간: ${kstTime}(UTC ${utcTime})
집결장: ${leader||"-"}
집결원: ${others.join(", ")}
병력수: ${power}명`;if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(()=>alert("복사되었습니다."),()=>fallbackCopy(text));}else{fallbackCopy(text);} }
function fallbackCopy(text){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');document.body.removeChild(ta);alert("복사되었습니다.");}

async function showAllUsers(){const usersSnap=await db.collection("users").get();const joined=new Set();state.parties.forEach(p=>normalizeMembers(p.members).forEach(n=>joined.add(n)));const all=[];usersSnap.forEach(doc=>{if(!isHiddenTestNickname(doc.id))all.push(doc.id);});all.sort((a,b)=>a.localeCompare(b,"ko"));const inUsers=all.filter(n=>joined.has(n));const outUsers=all.filter(n=>!joined.has(n));el.joinedUsers.innerHTML=renderNameColumns(inUsers);el.notJoinedUsers.innerHTML=renderNameColumns(outUsers);openOverlay();el.userModal.classList.remove("hidden");}
window.showAllUsers=showAllUsers;
function renderNameColumns(arr){if(!arr.length)return`<div class="name-item">(없음)</div>`;return arr.map(v=>`<div class="name-item">${escapeHtml(v)}</div>`).join("");}
function closeUserModal(){el.userModal.classList.add("hidden");closeOverlay();}
window.closeUserModal=closeUserModal;

async function showAdminLogs(){if(!state.isAdmin){alert("권한이 없습니다.");return;}const snap=await db.collection("adminLogs").orderBy("createdAt","desc").limit(50).get();const items=[];snap.forEach(doc=>items.push({id:doc.id,...doc.data()}));el.logList.innerHTML=items.length?items.map(log=>`<div class="log-item"><div class="log-top"><div class="log-action">${escapeHtml(log.action||"")}</div><div class="muted">${log.admin?escapeHtml(log.admin):""}</div></div><div class="muted">이벤트: ${escapeHtml(log.event||"-")}</div><div class="muted">${escapeHtml(JSON.stringify(log.payload||{}))}</div>${!log.undone?`<button class="undo-btn" onclick="undoAdminLog('${escapeJs(log.id)}')">실행취소</button>`:`<div class="muted">실행취소됨</div>`}</div>`).join(""):`<div class="empty-card">운영 로그가 없습니다.</div>`;openOverlay();el.logModal.classList.remove("hidden");closeAdminMenu();}
window.showAdminLogs=showAdminLogs;
function closeLogModal(){el.logModal.classList.add("hidden");closeOverlay();}
window.closeLogModal=closeLogModal;
async function undoAdminLog(id){const ref=db.collection("adminLogs").doc(id);const snap=await ref.get();if(!snap.exists)return;const log=snap.data()||{};if(log.undone)return;const p=log.payload||{};if(log.action==="set_rally_leader"&&log.event==="ruins"&&p.partyId){await partiesRef("ruins").doc(p.partyId).update({rallyLeader:""});}if(log.action==="kick_member"&&log.event&&p.partyId&&p.memberName){const pref=partiesRef(log.event).doc(p.partyId);const psnap=await pref.get();if(psnap.exists){const d=psnap.data()||{};const members=normalizeMembers(d.members);if(!members.includes(p.memberName)){members.push(p.memberName);await pref.update({members});}}}await ref.update({undone:true,undoneAt:firebase.firestore.FieldValue.serverTimestamp(),undoneBy:state.currentUser});showAdminLogs();}
window.undoAdminLog=undoAdminLog;

document.addEventListener("DOMContentLoaded",tryAutoLogin);
